apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    template: cronjob-prune-builds-deployments
  name: {{ .Values.namespace }}-{{ .Values.prune_type }}-pruners
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: cluster-admin
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  name: {{ .Values.prune_type }}-{{ .Values.job_service_account }}
  namespace: {{ .Values.namespace }}
