apiVersion: rbac.authorization.k8s.io/v1
groupNames: null
kind: ClusterRoleBinding
metadata:
  labels:
    template: cronjob-ldap-group-sync
  name: {{ .Values.namespace }}-ldap-group-syncers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: ldap-group-syncer
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  name: {{ .Values.job_service_account }}
  namespace: {{ .Values.namespace }}
